platform :ios, '13.0'
use_frameworks!

target 'Sketch_Example' do
  pod 'Sketch', :path => '../'

  target 'Sketch_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 6.0'
    pod 'Nimble', '~> 12.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
